/* ============================================================================
   Foundry import macro - generated by campaigns/tools/foundryExport
   Verified on Foundry VTT 14.363 / pf2e 8.2.0.

   HOW TO USE: Macro Directory -> Create Macro -> Type: "script" -> paste this ->
   Save -> double-click to run (as GM). It creates one Actor folder named below,
   imports one actor per distinct creature (you drop N tokens yourself), renames
   imported NPCs, makes blank npc actors for narrative-only NPCs, and builds each
   loot "chest" actor with its items + coins. Re-running is blocked if the folder
   already exists - delete it first to rebuild.
   ========================================================================== */
(async () => {
  if (!game.user.isGM) return ui.notifications.error("Run this macro as the GM.");

  const SPEC = {
  "folder": "Below the Quiet Docks",
  "monsters": [
    {
      "name": "Hunting Spider",
      "count": 12
    },
    {
      "name": "Ogre Spider",
      "count": 1
    },
    {
      "name": "Giant Tarantula",
      "count": 1
    },
    {
      "name": "Brine Shark",
      "count": 4
    },
    {
      "name": "Behir",
      "count": 1
    },
    {
      "name": "Skeleton Guard",
      "count": 4
    }
  ],
  "npcs": [
    {
      "name": "The Venom Queen",
      "base": "Giant Tarantula"
    },
    {
      "name": "The Tomb-Keeper",
      "base": "Ghost Commoner"
    },
    {
      "name": "Sable Rei"
    },
    {
      "name": "Davo Kenn"
    },
    {
      "name": "Lena Marsh"
    },
    {
      "name": "Oryn"
    },
    {
      "name": "Petra Voss"
    },
    {
      "name": "Corin Vale"
    },
    {
      "name": "Moss"
    }
  ],
  "chests": [
    {
      "name": "Storage Room Cache",
      "items": [
        {
          "name": "Antidote (Moderate)",
          "count": 1
        }
      ],
      "coins": {}
    },
    {
      "name": "Spring Rim",
      "items": [
        {
          "name": "Elixir of Life (Lesser)",
          "count": 1
        }
      ],
      "coins": {}
    },
    {
      "name": "Smuggler's Kit",
      "items": [
        {
          "name": "Darkvision Elixir (Moderate)",
          "count": 1
        }
      ],
      "coins": {}
    },
    {
      "name": "Corin's Pack",
      "items": [
        {
          "name": "Poisonous Dagger",
          "count": 1
        }
      ],
      "coins": {}
    },
    {
      "name": "Moss's Oilcloth",
      "items": [
        {
          "name": "Aeon Stone (Crescent)",
          "count": 1
        }
      ],
      "coins": {}
    }
  ],
  "areas": [
    {
      "label": "1 · The Docks",
      "rects": [
        {
          "left": 66.7,
          "top": 93.2,
          "width": 33.3,
          "height": 6.8
        }
      ]
    },
    {
      "label": "2 · Beast Cave",
      "rects": [
        {
          "left": 81.1,
          "top": 71.7,
          "width": 18.9,
          "height": 17.2
        }
      ]
    },
    {
      "label": "3 · Old Crypt",
      "rects": [
        {
          "left": 83.9,
          "top": 52.6,
          "width": 13.8,
          "height": 18
        }
      ]
    },
    {
      "label": "4 · The Springs",
      "rects": [
        {
          "left": 54.6,
          "top": 54.9,
          "width": 21.4,
          "height": 10.4
        }
      ]
    },
    {
      "label": "5 · The Sewer Ways",
      "rects": [
        {
          "left": 28.2,
          "top": 70.8,
          "width": 52.6,
          "height": 16.5
        },
        {
          "left": 65.5,
          "top": 67.8,
          "width": 14.7,
          "height": 4.3
        }
      ]
    },
    {
      "label": "6 · Smuggler Storage",
      "rects": [
        {
          "left": 45,
          "top": 59.8,
          "width": 6.5,
          "height": 8.2
        }
      ]
    },
    {
      "label": "7 · Abandoned Room",
      "rects": [
        {
          "left": 30.5,
          "top": 56.7,
          "width": 12.5,
          "height": 13.1
        }
      ]
    },
    {
      "label": "8 · Spring",
      "rects": [
        {
          "left": 16.5,
          "top": 69.3,
          "width": 9.6,
          "height": 5.1
        }
      ]
    },
    {
      "label": "9 · Smuggler Room",
      "rects": [
        {
          "left": 5.2,
          "top": 87.4,
          "width": 11.7,
          "height": 7
        }
      ]
    },
    {
      "label": "10 · Deep Pool",
      "rects": [
        {
          "left": 1.4,
          "top": 35.9,
          "width": 14.4,
          "height": 11
        }
      ]
    },
    {
      "label": "11 · Storage Room",
      "rects": [
        {
          "left": 22.7,
          "top": 19,
          "width": 9.2,
          "height": 15.4
        }
      ]
    },
    {
      "label": "12 · Spider Smaller Lair",
      "rects": [
        {
          "left": 8,
          "top": 1.9,
          "width": 16.1,
          "height": 10.1
        }
      ]
    },
    {
      "label": "13 · Queen Room",
      "rects": [
        {
          "left": 54.8,
          "top": 1.6,
          "width": 45.2,
          "height": 22.9
        }
      ]
    },
    {
      "label": "14 · Old Prison",
      "rects": [
        {
          "left": 71.1,
          "top": 41.3,
          "width": 12.7,
          "height": 10.9
        }
      ]
    },
    {
      "label": "15 · Survivor Room",
      "rects": [
        {
          "left": 42.7,
          "top": 50.2,
          "width": 10.5,
          "height": 6.5
        }
      ]
    },
    {
      "label": "16 · Spider Hallway",
      "rects": [
        {
          "left": 41.4,
          "top": 37.6,
          "width": 14.3,
          "height": 10.8
        },
        {
          "left": 51.2,
          "top": 35,
          "width": 14.9,
          "height": 5.7
        },
        {
          "left": 17.3,
          "top": 36.9,
          "width": 17.6,
          "height": 8.6
        },
        {
          "left": 31.5,
          "top": 39.6,
          "width": 12.2,
          "height": 9.7
        }
      ]
    },
    {
      "label": "17 · The Dead Room",
      "rects": [
        {
          "left": 28.2,
          "top": 2.1,
          "width": 15.6,
          "height": 9.9
        }
      ]
    },
    {
      "label": "18 · Survivor Room",
      "rects": [
        {
          "left": 24.5,
          "top": 49.9,
          "width": 8.6,
          "height": 6.2
        }
      ]
    }
  ],
  "placement": [
    {
      "area": "8 · Spring",
      "name": "Brine Shark",
      "count": 2
    },
    {
      "area": "10 · Deep Pool",
      "name": "Brine Shark",
      "count": 2
    },
    {
      "area": "2 · Beast Cave",
      "name": "Behir",
      "count": 1
    },
    {
      "area": "16 · Spider Hallway",
      "name": "Ogre Spider",
      "count": 1
    },
    {
      "area": "16 · Spider Hallway",
      "name": "Hunting Spider",
      "count": 6
    },
    {
      "area": "12 · Spider Smaller Lair",
      "name": "Giant Tarantula",
      "count": 1
    },
    {
      "area": "12 · Spider Smaller Lair",
      "name": "Hunting Spider",
      "count": 2
    },
    {
      "area": "13 · Queen Room",
      "name": "The Venom Queen",
      "count": 1
    },
    {
      "area": "13 · Queen Room",
      "name": "Hunting Spider",
      "count": 4
    },
    {
      "area": "3 · Old Crypt",
      "name": "The Tomb-Keeper",
      "count": 1
    },
    {
      "area": "3 · Old Crypt",
      "name": "Skeleton Guard",
      "count": 4
    },
    {
      "area": "15 · Survivor Room",
      "name": "Davo Kenn",
      "count": 1,
      "disposition": "friendly"
    },
    {
      "area": "18 · Survivor Room",
      "name": "Lena Marsh",
      "count": 1,
      "disposition": "friendly"
    },
    {
      "area": "13 · Queen Room",
      "name": "Oryn",
      "count": 1,
      "disposition": "friendly"
    },
    {
      "area": "9 · Smuggler Room",
      "name": "Petra Voss",
      "count": 1,
      "disposition": "friendly"
    },
    {
      "area": "17 · The Dead Room",
      "name": "Corin Vale",
      "count": 1,
      "disposition": "neutral"
    },
    {
      "area": "7 · Abandoned Room",
      "name": "Moss",
      "count": 1,
      "disposition": "neutral"
    }
  ]
};
  const ACTOR_PRIORITY = ["pf2e.pathfinder-monster-core", "pf2e.pathfinder-monster-core-2", "pf2e.pathfinder-npc-core", "pf2e.npc-gallery", "pf2e.pathfinder-bestiary", "pf2e.pathfinder-bestiary-2", "pf2e.pathfinder-bestiary-3"];
  const ITEM_PRIORITY = ["pf2e.equipment-srd"];

  const orderPacks = (docType, priority) => {
    const all = game.packs.filter(p => p.documentName === docType);
    const head = priority.map(id => all.find(p => p.collection === id)).filter(Boolean);
    const tail = all.filter(p => !priority.includes(p.collection));
    return [...head, ...tail];
  };
  const actorPacks = orderPacks("Actor", ACTOR_PRIORITY);
  const itemPacks = orderPacks("Item", ITEM_PRIORITY);

  const idx = async p => { if (!p.indexed) await p.getIndex(); return p; };

  async function resolve(name, packHint, ordered) {
    if (packHint) {
      const id = String(packHint).includes(".") ? packHint : ("pf2e." + packHint);
      const p = game.packs.get(id);
      if (p) { await idx(p); const e = p.index.getName(name); if (e) return { pack: p, id: e._id }; }
    }
    for (const p of ordered) {
      await idx(p);
      const e = p.index.getName(name);
      if (e) return { pack: p, id: e._id };
    }
    return null;
  }

  // Guard: do not silently double-import on a re-run.
  if (game.folders.find(f => f.type === "Actor" && f.name === SPEC.folder))
    return ui.notifications.error(`An Actor folder "${SPEC.folder}" already exists. Delete it, then re-run.`);
  const folder = await Folder.create({ name: SPEC.folder, type: "Actor" });

  // Tidy subfolders, created lazily so empty categories leave no empty folder.
  const _sub = {};
  const sub = async name => {
    if (!_sub[name]) _sub[name] = await Folder.create({ name, type: "Actor", folder: folder.id });
    return _sub[name].id;
  };

  const made = [], missing = [], byName = {};

  for (const m of (SPEC.monsters || [])) {
    const hit = await resolve(m.name, m.pack, actorPacks);
    if (!hit) { missing.push("monster: " + m.name); continue; }
    // keepId:false: Foundry v14 keeps the source _id by default, so importing the
    // same creature twice (e.g. a boss sharing a base with regular monsters) would
    // collide; a fresh id per import keeps them distinct.
    const a = await game.actors.importFromCompendium(hit.pack, hit.id, { folder: await sub("Monsters") }, { keepId: false });
    byName[a.name] = a;
    made.push(`${m.count || 1}x ${a.name}  (drop ${m.count || 1} token${(m.count || 1) === 1 ? "" : "s"})`);
  }

  for (const n of (SPEC.npcs || [])) {
    if (n.base) {
      const hit = await resolve(n.base, n.pack, actorPacks);
      if (!hit) { missing.push("npc base: " + n.base + " (for " + n.name + ")"); continue; }
      // Rename both the actor and its prototype token, else placed/dropped tokens
      // keep the base creature's name (the actor is renamed but the token is not).
      const a = await game.actors.importFromCompendium(hit.pack, hit.id, { folder: await sub("NPCs"), name: n.name, "prototypeToken.name": n.name }, { keepId: false });
      byName[a.name] = a;
      made.push("NPC " + a.name + "  (from " + n.base + ")");
    } else {
      const a = await Actor.create({ name: n.name, type: "npc", folder: await sub("NPCs") });
      byName[a.name] = a;
      made.push("NPC " + a.name + "  (blank - statless)");
    }
  }

  for (const c of (SPEC.chests || [])) {
    const chest = await Actor.create({ name: c.name, type: "loot", folder: await sub("Loot") });
    const objs = [];
    for (const it of (c.items || [])) {
      const hit = await resolve(it.name, it.pack, itemPacks);
      if (!hit) { missing.push("item: " + it.name + " (for " + c.name + ")"); continue; }
      const obj = (await hit.pack.getDocument(hit.id)).toObject();
      if (it.count && it.count > 1) obj.system.quantity = it.count;
      objs.push(obj);
    }
    if (objs.length) await chest.createEmbeddedDocuments("Item", objs);
    if (c.coins && Object.keys(c.coins).length) await chest.inventory.addCoins(c.coins);
    made.push("Chest " + chest.name + "  (" + objs.length + " item stack" + (objs.length === 1 ? "" : "s") +
      (c.coins && Object.keys(c.coins).length ? " + coins" : "") + ")");
  }

  // ---- optional token placement on the active/viewed scene ----------------
  // Areas are the map-area-editor export (% rects); placement says which actor
  // goes in which area. Tokens fan out, grid-snapped, on the scene you have open.
  const placements = SPEC.placement || [];
  const scene = game.scenes.viewed || game.scenes.active;
  let placed = 0;
  if (placements.length && !scene) {
    missing.push("no active scene - tokens not placed (open the quest scene, delete the folder, re-run)");
  } else if (placements.length) {
    const d = scene.dimensions, g = d.size;
    const DISP = { hostile: -1, neutral: 0, friendly: 1, secret: -2 };
    // pf2e derives a token's disposition from its actor's alliance and ignores a
    // bare disposition arg, so set alliance to colour survivors/foes correctly.
    const ALLIANCE = { hostile: "opposition", friendly: "party", neutral: null };
    const areas = SPEC.areas || [];
    const findArea = ref => {
      if (typeof ref === "number") return areas[ref];
      const k = String(ref).trim().toLowerCase();
      return areas.find(a => String(a.label || "").trim().toLowerCase() === k);
    };
    const center = a => {                      // bounding box of the area's rects -> center px
      const rs = a.rects || [];
      const L = Math.min(...rs.map(r => r.left)), T = Math.min(...rs.map(r => r.top));
      const R = Math.max(...rs.map(r => r.left + r.width)), B = Math.max(...rs.map(r => r.top + r.height));
      return { cx: d.sceneX + (L + R) / 200 * d.sceneWidth, cy: d.sceneY + (T + B) / 200 * d.sceneHeight };
    };
    const tokenData = [];
    for (const p of placements) {
      const area = findArea(p.area), actor = byName[p.name];
      if (!area || !(area.rects || []).length) { missing.push("placement area: " + p.area); continue; }
      if (!actor) { missing.push("placement actor: " + p.name + " (import it first)"); continue; }
      if (p.disposition && p.disposition in ALLIANCE && actor.system?.details && "alliance" in actor.system.details) {
        await actor.update({ "system.details.alliance": ALLIANCE[p.disposition] });
      }
      const { cx, cy } = center(area);
      const n = p.count || 1, tw = actor.prototypeToken?.width || 1, step = g * Math.max(1, tw);
      const cols = Math.ceil(Math.sqrt(n)), rows = Math.ceil(n / cols);
      const disp = (p.disposition in DISP) ? DISP[p.disposition] : -1;
      for (let i = 0; i < n; i++) {
        const ox = (i % cols - (cols - 1) / 2) * step, oy = (Math.floor(i / cols) - (rows - 1) / 2) * step;
        const x = Math.round((cx + ox - tw * g / 2) / g) * g, y = Math.round((cy + oy - tw * g / 2) / g) * g;
        tokenData.push((await actor.getTokenDocument({ x, y, disposition: disp })).toObject());
      }
      placed += n;
    }
    if (tokenData.length) await scene.createEmbeddedDocuments("Token", tokenData);
    if (placed) made.push(`Placed ${placed} token(s) on scene "${scene.name}"`);
  }

  const body = `<h3>Imported "${SPEC.folder}"</h3><ul>${made.map(x => "<li>" + x + "</li>").join("")}</ul>` +
    (missing.length ? `<p style="color:#b33"><b>Unresolved (${missing.length}):</b><br>${missing.join("<br>")}</p>`
      + `<p><i>Check the name spelling, or add a "pack" hint for the exact compendium.</i></p>` : "");
  await ChatMessage.create({ content: body, whisper: [game.user.id] });
  ui.notifications.info(`Imported "${SPEC.folder}": ${made.length} actor(s)` +
    (placed ? `, ${placed} token(s) on "${scene.name}"` : "") +
    (missing.length ? `, ${missing.length} unresolved (see chat)` : "") + ".");
})();
